### ISSUE TITLE
Fix broken Travis OS X build

### ISSUE THREAD

**Issue by Choc13** [wintoncode/Winton.AspNetCore.Seo#11]
Travis builds are failing on OS X with the error: `Homebrew must be run under Ruby 2.3! (RuntimeError)`. There is an [issue open](https://github.com/travis-ci/travis-ci/issues/8552) on the Travis repo to fix this, but for the time being the suggestion for .NET Core projects is to the change the build script to something like the following:

```yml
language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode9      
      sudo: required        
before_install:
  - brew update
  - curl https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
  - chmod +x dotnet-install.sh
  - ./dotnet-install.sh --channel 2.0
```
